# アルコネ（全マス使用ナンバーリンク）作問アルゴリズム

ここでは、「唯一解を持つアルコネ（全マスを使用するナンバーリンク）」を生成するための本格的な作問アルゴリズムを実装しています。

### アルゴリズムの流れ：
1. **フェーズ1（前進分割）**: 縦ジグザグのハミルトンパスを多数のパスに分割し、別解（全マス使用・短絡解）があればエッジを切断してペアを追加することで、高速に唯一解を確立します。
2. **フェーズ2（後退結合）**: 隣接するパスを順番に結合してみて、唯一解が保たれるなら結合してペア数を減らしていきます。

この「前進分割→後退結合」の2フェーズ設計により、確実に全マス使用・唯一解を実現しながら、ペア数を目標値（例: 10以下）まで最小化できます。

In [1]:
import arukone_gen
import SaveNumlinkFormat
import numpy as np
import time

In [2]:
h, w = 10, 10
max_n = 7
print(f"--- {h}x{w} 全マス使用アルコネ 最大{max_n}ペア で作問中 ---")
t0 = time.time()
grid, paths = arukone_gen.build_arukone(h, w, max_n, verbose=True)
elapsed = time.time() - t0
n = len(paths)
print(f"\n★ 完成！ ペア数={n}  ({elapsed:.2f}秒)")
print(np.array(grid))


--- 10x10 全マス使用アルコネ 最大7ペア で作問中 ---
  フェーズ1完了: 22ペアの唯一解 (0.1秒)
  22 -> 21 ペア (0.1秒)
  21 -> 20 ペア (0.1秒)
  20 -> 19 ペア (0.1秒)
  19 -> 18 ペア (0.1秒)
  18 -> 17 ペア (0.1秒)
  17 -> 16 ペア (0.1秒)
  16 -> 15 ペア (0.1秒)
  15 -> 14 ペア (0.1秒)
  14 -> 13 ペア (0.1秒)
  13 -> 12 ペア (0.1秒)
  12 -> 11 ペア (0.1秒)
  11 -> 10 ペア (0.1秒)
  10 -> 9 ペア (0.1秒)
  9 -> 8 ペア (0.1秒)
  ✓ 完成 n=8 (0.25秒)

★ 完成！ ペア数=8  (0.40秒)
[[0 0 0 8 0 0 4 0 2 5]
 [0 3 0 7 0 0 5 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [6 0 6 0 8 0 0 2 1 0]
 [3 0 7 0 4 0 0 0 0 0]]


In [6]:

SaveNumlinkFormat.save_numlin_format(grid, "output.txt")

Exported to output.txt
