In [1]:
import numpy as np
import random
from NumberLinkSolver import NumberLinkSolver

In [12]:
h = 6
w = 6

n = 5
d = 2

r = h * w

arr = [i for i in range(1, n + 1) for _ in range(2)]

for i in range(1000000):
    indices = random.sample(range(r), n * 2)
    # 距離が近すぎる数字がある場合スキップする
    if any(abs(p1 // w - p2 // w) + abs(p1 % w - p2 % w) <= d for p1, p2 in zip(indices[::2], indices[1::2])):
        continue

    line = np.zeros(r, dtype=int)
    line[indices] = arr

    grid = line.reshape(h, w)
    parsed_grid = grid.tolist()

    solution = NumberLinkSolver(parsed_grid).solve()

    if solution and not any(0 in row for row in solution):
        print(i)
        print(grid)
        for row in solution:
            print(row)
        break


176181
[[2 0 0 5 1 0]
 [0 0 0 0 0 0]
 [0 5 4 3 0 0]
 [0 0 0 0 0 0]
 [0 3 1 4 0 0]
 [0 2 0 0 0 0]]
[2, 5, 5, 5, 1, 1]
[2, 5, 4, 4, 4, 1]
[2, 5, 4, 3, 4, 1]
[2, 3, 3, 3, 4, 1]
[2, 3, 1, 4, 4, 1]
[2, 2, 1, 1, 1, 1]
