In [1]:
import numpy as np
import random
from NumberLinkSolver import NumberLinkSolver

In [10]:
h = 6
w = 6

n = 5

r = h * w

arr = [i for i in range(1, n + 1) for _ in range(2)]

for i in range(100000):
    indices = random.sample(range(r), n * 2)
    if any(abs(p1 // w - p2 // w) + abs(p1 % w - p2 % w) == 1 for p1, p2 in zip(indices[::2], indices[1::2])):
        continue

    line = np.zeros(r, dtype=int)
    line[indices] = arr

    grid = line.reshape(h, w)
    parsed_grid = grid.tolist()

    solution = NumberLinkSolver(parsed_grid).solve()

    if solution and not any(0 in row for row in solution):
        print(i)
        print(grid)
        for row in solution:
            print(row)
        break


82126
[[0 0 0 0 0 3]
 [5 4 0 0 0 2]
 [0 3 0 5 0 0]
 [0 0 0 1 0 0]
 [0 4 1 0 0 0]
 [0 0 0 0 0 2]]
[5, 5, 5, 5, 3, 3]
[5, 4, 4, 5, 3, 2]
[3, 3, 4, 5, 3, 2]
[3, 4, 4, 1, 3, 2]
[3, 4, 1, 1, 3, 2]
[3, 3, 3, 3, 3, 2]
