In [9]:
import arukone_gen
import SaveNumlinkFormat
import numpy as np
import time
from datetime import datetime

h, w = 10, 10
print(f"--- {h}x{w} 全マス使用ナンバーリンク作問中 ---")
t0 = time.time()
grid, paths = arukone_gen.build_arukone(h, w, 5, True)

elapsed = time.time() - t0
print(f"\n★ 完成！ ペア数={len(paths)}  ({elapsed:.2f}秒)")
print(np.array(grid))

print(SaveNumlinkFormat.generate_numlin_url(w, h, [i for r in grid for i in r]))

--- 10x10 全マス使用ナンバーリンク作問中 ---
  フェーズ1完了: 21ペアの唯一解 (0.3秒)
  21 -> 20 ペア (0.3秒)
  20 -> 19 ペア (0.3秒)
  19 -> 18 ペア (0.3秒)
  18 -> 17 ペア (0.3秒)
  17 -> 16 ペア (0.3秒)
  16 -> 15 ペア (0.3秒)
  15 -> 14 ペア (0.3秒)
  14 -> 13 ペア (0.3秒)
  13 -> 12 ペア (0.3秒)
  12 -> 11 ペア (0.3秒)
  11 -> 10 ペア (0.3秒)
  ✓ 完成 n=10 (0.34秒)

★ 完成！ ペア数=10  (0.40秒)
[[ 5 -1 -1 -1 -1 -1  7  9 -1 -1]
 [-1 -1  2 -1 -1 -1 -1 -1  2 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 10 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1  6 -1]
 [-1  7 -1 -1 -1 -1 -1  9 -1 -1]
 [-1 -1 -1  6 -1 -1  3 -1 -1  4]
 [ 8 -1 -1 -1 -1  3 10 -1  4 -1]
 [-1 -1 -1 -1 -1 -1  1 -1 -1  1]
 [-1 -1 -1 -1  8 -1 -1 -1 -1  5]]
https://puzz.link/p?numlin/10/10/5k79j2k2tat6h7k9k6h3h48j3ag4m1h1j8j5


In [10]:
SaveNumlinkFormat.save_numlin_format(grid, f"../problems/numlin_w{w}-h{h}-n{len(paths)}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt")

Exported to ../problems/numlin_w10-h10-n10_20260314_175429.txt
