# アルコネ（全マス使用ナンバーリンク）作問アルゴリズム

ここでは、「唯一解を持つアルコネ（全マスを使用するナンバーリンク）」を生成するための本格的な作問アルゴリズムを実装しています。

### アルゴリズムの流れ：
1. **フェーズ1（前進分割）**: 縦ジグザグのハミルトンパスを多数のパスに分割し、別解（全マス使用・短絡解）があればエッジを切断してペアを追加することで、高速に唯一解を確立します。
2. **フェーズ2（後退結合）**: 隣接するパスを順番に結合してみて、唯一解が保たれるなら結合してペア数を減らしていきます。

この「前進分割→後退結合」の2フェーズ設計により、確実に全マス使用・唯一解を実現しながら、ペア数を目標値（例: 10以下）まで最小化できます。

In [1]:
import arukone_gen
import SaveNumlinkFormat
import numpy as np
import time
from datetime import datetime

In [ ]:
h, w = 12, 12
n = 9
print(f"--- {h}x{w} 全マス使用ナンバーリンク 最大{n}ペア で作問中 ---")
t0 = time.time()
grid, paths = arukone_gen.build_arukone(h, w, n, verbose=False)

elapsed = time.time() - t0
n = len(paths)
print(f"\n★ 完成！ ペア数={n}  ({elapsed:.2f}秒)")
print(np.array(grid))

filename = f"problems/numlin_h{h}-w{w}-n{n}s_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
SaveNumlinkFormat.save_numlin_format(grid, filename)



--- 12x12 全マス使用ナンバーリンク 最大9ペア で作問中 ---

★ 完成！ ペア数=12  (502.08秒)
[[ 5  0  0 12  0  0  0  0  0  0  0  8]
 [ 6  0  0  0  0  3  4  0  0  0  0  0]
 [11  0  4  5  3  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  2  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  0 10  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0]
 [ 7 11  0  0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  0  0  7  0  0  0]]
Exported to numlin_h12-w12-n12s_20260307_040835.txt
